//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kudashova320.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> IDType { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<int> IDHuman { get; set; }
    
        public virtual Human Human { get; set; }
        public virtual tYPE tYPE { get; set; }
    }
}
